__version__:
  serializer: 1
  data: 10
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 4
        Brightness: 0
        ExposureTime: 35000
        Gain: 1
  Diagnostics:
    Enabled: no
  Experimental:
    Engine: phase
  Processing:
    Color:
      Balance:
        Blue: 1.4
        Green: 1
        Red: 1
      Experimental:
        ToneMapping:
          Enabled: always
      Gamma: 1
    Filters:
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: yes
            Strength: 0.5
          Removal:
            Enabled: no
            Threshold: 0.2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 5
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 10
      Reflection:
        Removal:
          Enabled: yes
      Smoothing:
        Gaussian:
          Enabled: yes
          Sigma: 1.25
